docker_version: 17.05.0.ce
#docker_direct_lvm: true
docker_direct_lvm: false
docker_thinpooldev: /dev/vdb
#k8s
k8s_temp_dir: /opt/k8s_init
#ceph
#ceph: true
ceph: false
ceph_version: jewel
#glusterfs
#glusterfs: true
glusterfs: false
glusterfs_version: 310
