---
#########################################################################
# tested on centos 7
# 2017-06-12
# created by : lvzhijun
# others : init docker
# 1.install docker
# 2.add aliyun mirror
########################################################################
# base on vm image:CentOS7.2_1612
- name: copy docker repo file
  copy: src=docker.repo dest=/etc/yum.repos.d/docker.repo owner=root group=root mode=0640
# install docker engine
- name: install docker engine
  yum: name={{ item }} state=present
  with_items:
        - docker-engine-{{ docker_version }}
        - docker-engine-selinux-{{ docker_version }}
        - device-mapper-persistent-data
        - lvm2
# start docker
- name: create docker dir
  file: name=/etc/docker state=directory mode=700
# add registry-mirrors
- name: copy daemon.json
  template: src=daemon.json dest=/etc/docker/daemon.json owner=root group=root mode=0640

- include: direct-lvm.yml
  when: docker_direct_lvm == true

- name: restart docker again
  service: name=docker state=started
#docker_direct-lvm: true
#docker_thinpooldev: /dev/vdb
