apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: slow
provisioner: kubernetes.io/glusterfs
parameters:
    resturl: "http://{{ glusterfs_vip }}:{{ heketi_port }}"
    clusterid: "{{ clusterid_result['stdout'] }}"
    restuser: "admin"
    secretNamespace: "default"
    secretName: "heketi-secret"
    gidMin: "40000"
    gidMax: "50000"
    volumetype: "replicate:2"
---
apiVersion: v1
kind: Secret
metadata:
  name: heketi-secret
  namespace: default
data:
  # base64 encoded password. E.g.: echo -n "mypassword" | base64
     key: {{ heketi_key_base64_result['stdout'] }} 
type: kubernetes.io/glusterfs
