---
#########################################################################
# tested on centos 7
# 2017-07-19
# created by : lvzhijun
########################################################################
#
# 
- name: install glusterfs-release
  yum: name=centos-release-gluster{{ glusterfs_version }}  state=present

- name: install glusterfs-server
  yum: name=glusterfs-server,heketi-{{ heketi_version }},heketi-client-{{ heketi_version }} state=present

- name: enable glusterd
  service: name=glusterd state=started enabled=yes

- name: ssh-keygen
  local_action: shell echo -e  'y\n' | ssh-keygen -C 'from_ansible-kubeadm' -t rsa -f /tmp/heketi_key -N '' && chmod 644 /tmp/heketi_key
  when: inventory_hostname == groups['glusterfs'][0]

- name: copy key files
  copy: src=/tmp/{{ item }} dest=/etc/heketi/ mode=600 owner=heketi
  with_items: 
       - heketi_key
       - heketi_key.pub

- name: rm ssh-keygen
  local_action: shell rm  /tmp/heketi_key  /tmp/heketi_key.pub
  when: inventory_hostname == groups['glusterfs'][0]

- name: enable ssh authorized_keys
  shell:  test -d $HOME/.ssh || mkdir -m 700 $HOME/.ssh

- name: enable ssh authorized_keys
  shell: cat /etc/heketi/heketi_key.pub >> $HOME/.ssh/authorized_keys && chmod 600 $HOME/.ssh/authorized_keys

- name: backup heketi database
  shell: cp -r /var/lib/heketi /var/lib/heketi.`date +%s` || rm -rf /var/lib/heketi/
  ignore_errors: yes

- name: template heketi.json
  template: src=heketi.json dest=/etc/heketi/heketi.json 

- name: start heketi
  service: name=heketi state=restarted

- name: template topology.json
  template: src=topology.json dest=/etc/heketi/

- name: create glusterfs topology
  shell: heketi-cli --server http://localhost:{{ heketi_port }} --user admin --secret {{ heketi_key }} topology load --json=/etc/heketi/topology.json
  when: glusterfs_vip is defined

- name: get glusterfs clusterid
  shell: heketi-cli --server http://localhost:{{ heketi_port }} --user admin --secret {{ heketi_key }} cluster list |sed -n '2p'
  register: clusterid_result
  when: glusterfs_vip is defined
  tags:
     - test

- name: get glusterfs heketi_key_base64
  shell: echo -n "{{ heketi_key }}" | base64
  register: heketi_key_base64_result
  when: glusterfs_vip is defined
  tags:
     - test

- name: template glusterfs-sc.yaml
  template: src=glusterfs-sc.yaml dest=/etc/heketi/
  when: glusterfs_vip is defined
  tags:
     - test

- name: create StorageClass in k8s
  shell: source $HOME/.bash_profile && kubectl apply -f /etc/heketi/glusterfs-sc.yaml
  when: glusterfs_vip is defined
  tags:
     - test
#- name: create glusterfs volume
#  shell: heketi-cli --server http://localhost:{{ heketi_port }} --user admin --secret {{ heketi_key }} volume create --size={{ heketi_vol_size }} --replica={{ heketi_replica_size }}
#  when: glusterfs_vip is defined
# todo:
# k8s:dpv
# rsync /var/lib/heketi
#- name: test
#  shell: echo {{ vars['ansible_' + ka_interface]['ipv4']['address'] }}
#  tags: test
