---
#########################################################################
# tested on ubuntu 14
# 2017-08-26
# created by : lvzhijun
########################################################################
#
# 
- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'  and ansible_distribution_major_version == '14'

- include: centos.yml
  when: ansible_distribution == 'CentOS'  and ansible_distribution_major_version == '7'
